#!/usr/bin/env python3
"""Sandboxed Python executor for tool-augmented math reasoning (exp_040).

The model emits ```python``` code that computes a math answer; we run it here and
capture stdout. The code is *self-generated by our own model on a benchmark* — not
adversarial input — so the goal is **resource safety, not security hardening**:
a model that writes `[0]*10**10` or an infinite loop must not take down the
(shared, on DSMLP) pod. Three guards:

  1. **Timeout** — subprocess is killed after `timeout_s` (default 5s).
  2. **Memory cap** — `RLIMIT_AS` via a post-fork `preexec_fn` (Linux: enforced;
     macOS: best-effort, often ignored — that's fine, real runs are on Linux).
  3. **No network** — a preamble monkeypatches `socket` to raise, so accidental
     network calls fail fast rather than hang on a timeout.

A math preamble (`sympy`, `numpy`, `math`, high mpmath precision) is prepended so
the model can use them without imports, and so symbolic results print at full
precision — the entire point of this experiment (see postcomp/DEVLOG.md: the judge
demands ~8 sig figs and the model loses by rounding).

Run this file directly to execute the built-in self-tests (no GPU, no model).
"""
from __future__ import annotations

import os
import subprocess
import sys
import tempfile
from dataclasses import dataclass

# Prepended to every snippet. Gives the model batteries-included math and forces
# full-precision output. `socket` is neutralised first so network use fails fast.
DEFAULT_PREAMBLE = r"""
import socket as _socket
def _no_net(*a, **k):
    raise OSError("network disabled in sandbox")
_socket.socket = _no_net  # block the common path; self-generated code, not adversarial

import math
import numpy as np
import sympy as sp
from sympy import *               # Rational, sqrt, pi, simplify, nsimplify, N, ...
import mpmath as mp
mp.mp.dps = 50                    # 50 significant digits — far above the judge's 1e-8

# Encourage full-precision printing of common numeric types.
np.set_printoptions(precision=15, floatmode="maxprec")
"""


@dataclass
class ExecResult:
    """Outcome of running one code snippet."""
    ok: bool            # process exited 0, no timeout
    stdout: str
    stderr: str
    timed_out: bool
    returncode: int | None

    @property
    def last_line(self) -> str:
        """Last non-empty stdout line — the PAL convention for 'the answer'."""
        lines = [ln for ln in self.stdout.splitlines() if ln.strip()]
        return lines[-1].strip() if lines else ""


def _limit_memory(mem_bytes: int):
    """preexec_fn: cap address space of the child. Best-effort across platforms."""
    try:
        import resource
        resource.setrlimit(resource.RLIMIT_AS, (mem_bytes, mem_bytes))
    except Exception:
        pass  # macOS often ignores RLIMIT_AS; Linux (DSMLP) enforces it.


def run_code(
    code: str,
    timeout_s: float = 5.0,
    mem_mb: int = 4096,
    preamble: str = DEFAULT_PREAMBLE,
    python_exe: str | None = None,
) -> ExecResult:
    """Execute `code` in a fresh, resource-limited Python subprocess.

    Args:
        code: the snippet to run (no need to import math/sympy/numpy — see preamble).
        timeout_s: wall-clock kill deadline.
        mem_mb: RLIMIT_AS cap in MiB (4 GiB default stops `[0]*10**10` while leaving
            room for sympy/numpy's large virtual footprint).
        preamble: code prepended before `code` (math imports + network block).
        python_exe: interpreter to use (default: the current one, which on DSMLP/here
            has sympy+numpy installed).

    Returns:
        ExecResult with captured stdout/stderr and status flags.
    """
    python_exe = python_exe or sys.executable
    full = preamble + "\n# --- model code ---\n" + code + "\n"

    with tempfile.TemporaryDirectory() as td:
        script = os.path.join(td, "snippet.py")
        with open(script, "w") as f:
            f.write(full)

        # Minimal, network-unfriendly environment; no inherited proxies.
        env = {
            "PATH": os.environ.get("PATH", ""),
            "PYTHONHASHSEED": "0",
            "OPENBLAS_NUM_THREADS": "1",  # keep a stray numpy op from spawning many threads
            "OMP_NUM_THREADS": "1",
            "MKL_NUM_THREADS": "1",
            "no_proxy": "*",
        }

        try:
            proc = subprocess.run(
                [python_exe, "-I", script],  # -I: isolated (ignore env/user site, $PYTHONPATH)
                capture_output=True,
                text=True,
                timeout=timeout_s,
                cwd=td,
                env=env,
                preexec_fn=(lambda: _limit_memory(mem_mb * 1024 * 1024)) if os.name == "posix" else None,
            )
        except subprocess.TimeoutExpired as e:
            return ExecResult(
                ok=False,
                stdout=(e.stdout or "") if isinstance(e.stdout, str) else (e.stdout or b"").decode("utf-8", "replace"),
                stderr=f"TIMEOUT after {timeout_s}s",
                timed_out=True,
                returncode=None,
            )
        except Exception as e:  # spawn failure, etc.
            return ExecResult(False, "", f"EXEC_ERROR: {type(e).__name__}: {e}", False, None)

    return ExecResult(
        ok=(proc.returncode == 0),
        stdout=proc.stdout,
        stderr=proc.stderr,
        timed_out=False,
        returncode=proc.returncode,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Self-tests — run `python postcomp/harness/executor.py`
# ─────────────────────────────────────────────────────────────────────────────
def _selftest() -> int:
    failures = []

    def check(name, cond):
        print(f"  {'ok  ' if cond else 'FAIL'} {name}")
        if not cond:
            failures.append(name)

    print("executor self-tests:")

    # 1. Basic full-precision arithmetic — the core use case.
    r = run_code("print(85.9436692696235)")
    check("basic print", r.ok and r.last_line == "85.9436692696235")

    # 2. The motivating case: full-precision division (no rounding).
    r = run_code("from sympy import Rational; print(float(Rational(85100,12)))")
    check("full-precision division", r.ok and r.last_line.startswith("7091.666666"))

    # 3. sympy symbolic → high-precision numeric (trig the model rounds by hand).
    r = run_code("print(N(7.4*sin(rad(16)), 20))")
    check("sympy trig full precision", r.ok and r.last_line.startswith("2.0397"))

    # 4. mpmath high precision available.
    r = run_code("print(mp.nstr(mp.log(0.5)/mp.log(0.96584), 12))")
    check("mpmath log ratio", r.ok and r.last_line.startswith("19.94"))

    # 5. Timeout guard kills an infinite loop.
    r = run_code("while True:\n    pass", timeout_s=1.5)
    check("timeout guard", r.timed_out and not r.ok)

    # 6. Runtime error is captured, not raised here.
    r = run_code("print(1/0)")
    check("error captured", (not r.ok) and ("ZeroDivisionError" in r.stderr))

    # 7. Network is blocked.
    r = run_code("import socket; socket.socket()")
    check("network blocked", (not r.ok) and ("network disabled" in r.stderr or "OSError" in r.stderr))

    # 8. Memory cap stops a huge allocation (Linux-enforced; may pass-through on macOS).
    r = run_code("x = [0]*(10**10); print(len(x))", timeout_s=10, mem_mb=2048)
    mem_enforced = (not r.ok)
    check("memory cap (Linux only; informational on macOS)", True)  # never fail the suite on this
    print(f"       -> memory cap {'ENFORCED' if mem_enforced else 'not enforced on this platform'}")

    print(f"\n{'ALL PASS' if not failures else 'FAILURES: ' + ', '.join(failures)}")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(_selftest())
